# Generated by Django 3.0.5 on 2020-07-29 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='timetablecolumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default=0)),
                ('c1', models.CharField(choices=[('monday', 'MONDAY'), ('tuesday', 'TUESDAY'), ('wednesday', 'WEDNESDAY'), ('thursday', 'THURSDAY'), ('friday', 'FRIDAY'), ('saturday', 'SATURDAY'), ('sunday', 'SUNDAY')], default='---', max_length=20)),
                ('c2', models.CharField(choices=[('sub1', 'SUB1'), ('sub2', 'SUB2'), ('sub3', 'SUB3'), ('sub4', 'SUB4'), ('sub5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---')], default='---', max_length=20)),
                ('c3', models.CharField(choices=[('sub1', 'SUB1'), ('sub2', 'SUB2'), ('sub3', 'SUB3'), ('sub4', 'SUB4'), ('sub5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---')], default='---', max_length=20)),
                ('c4', models.CharField(choices=[('sub1', 'SUB1'), ('sub2', 'SUB2'), ('sub3', 'SUB3'), ('sub4', 'SUB4'), ('sub5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---')], default='---', max_length=20)),
                ('c5', models.CharField(choices=[('sub1', 'SUB1'), ('sub2', 'SUB2'), ('sub3', 'SUB3'), ('sub4', 'SUB4'), ('sub5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---')], default='---', max_length=20)),
                ('c6', models.CharField(choices=[('sub1', 'SUB1'), ('sub2', 'SUB2'), ('sub3', 'SUB3'), ('sub4', 'SUB4'), ('sub5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---')], default='---', max_length=20)),
                ('c7', models.CharField(choices=[('sub1', 'SUB1'), ('sub2', 'SUB2'), ('sub3', 'SUB3'), ('sub4', 'SUB4'), ('sub5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---')], default='---', max_length=20)),
                ('c8', models.CharField(choices=[('sub1', 'SUB1'), ('sub2', 'SUB2'), ('sub3', 'SUB3'), ('sub4', 'SUB4'), ('sub5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---')], default='---', max_length=20)),
                ('c9', models.CharField(choices=[('sub1', 'SUB1'), ('sub2', 'SUB2'), ('sub3', 'SUB3'), ('sub4', 'SUB4'), ('sub5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---')], default='---', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='timetablerow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.CharField(default='---', max_length=20)),
                ('r2', models.CharField(default='---', max_length=20)),
                ('r3', models.CharField(default='---', max_length=20)),
                ('r4', models.CharField(default='---', max_length=20)),
                ('r5', models.CharField(default='---', max_length=20)),
                ('r6', models.CharField(default='---', max_length=20)),
                ('r7', models.CharField(default='---', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
