# Generated by Django 3.0.5 on 2020-07-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertt', '0002_auto_20200729_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timetablerow',
        ),
        migrations.AlterField(
            model_name='timetablecolumn',
            name='c1',
            field=models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='timetablecolumn',
            name='c2',
            field=models.CharField(choices=[('SUB1', 'SUB1'), ('SUB2', 'SUB2'), ('SUB3', 'SUB3'), ('SUB4', 'SUB4'), ('SUB5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---'), ('lunch', 'lunch'), ('lab', 'lab'), ('SWA', 'SWA')], default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='timetablecolumn',
            name='c3',
            field=models.CharField(choices=[('SUB1', 'SUB1'), ('SUB2', 'SUB2'), ('SUB3', 'SUB3'), ('SUB4', 'SUB4'), ('SUB5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---'), ('lunch', 'lunch'), ('lab', 'lab'), ('SWA', 'SWA')], default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='timetablecolumn',
            name='c4',
            field=models.CharField(choices=[('SUB1', 'SUB1'), ('SUB2', 'SUB2'), ('SUB3', 'SUB3'), ('SUB4', 'SUB4'), ('SUB5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---'), ('lunch', 'lunch'), ('lab', 'lab'), ('SWA', 'SWA')], default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='timetablecolumn',
            name='c5',
            field=models.CharField(choices=[('SUB1', 'SUB1'), ('SUB2', 'SUB2'), ('SUB3', 'SUB3'), ('SUB4', 'SUB4'), ('SUB5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---'), ('lunch', 'lunch'), ('lab', 'lab'), ('SWA', 'SWA')], default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='timetablecolumn',
            name='c6',
            field=models.CharField(choices=[('SUB1', 'SUB1'), ('SUB2', 'SUB2'), ('SUB3', 'SUB3'), ('SUB4', 'SUB4'), ('SUB5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---'), ('lunch', 'lunch'), ('lab', 'lab'), ('SWA', 'SWA')], default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='timetablecolumn',
            name='c7',
            field=models.CharField(choices=[('SUB1', 'SUB1'), ('SUB2', 'SUB2'), ('SUB3', 'SUB3'), ('SUB4', 'SUB4'), ('SUB5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---'), ('lunch', 'lunch'), ('lab', 'lab'), ('SWA', 'SWA')], default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='timetablecolumn',
            name='c8',
            field=models.CharField(choices=[('SUB1', 'SUB1'), ('SUB2', 'SUB2'), ('SUB3', 'SUB3'), ('SUB4', 'SUB4'), ('SUB5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---'), ('lunch', 'lunch'), ('lab', 'lab'), ('SWA', 'SWA')], default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='timetablecolumn',
            name='c9',
            field=models.CharField(choices=[('SUB1', 'SUB1'), ('SUB2', 'SUB2'), ('SUB3', 'SUB3'), ('SUB4', 'SUB4'), ('SUB5', 'SUB5'), ('counselling class', 'counselling class'), ('library', 'library'), ('seminar', 'seminar'), ('---', '---'), ('lunch', 'lunch'), ('lab', 'lab'), ('SWA', 'SWA')], default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='timetablecolumn',
            name='row',
            field=models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth'), ('fifth', 'fifth'), ('sixth', 'sixth')], max_length=15),
        ),
    ]
