# Generated by Django 3.0.5 on 2020-07-29 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usertt', '0003_auto_20200729_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='time_table',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usertt.timetablecolumn'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
