# Generated by Django 3.0.5 on 2020-07-30 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usertt', '0005_auto_20200730_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='user',
        ),
        migrations.AddField(
            model_name='timetablecolumn',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
