# Generated by Django 3.0.5 on 2020-07-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertt', '0006_auto_20200730_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablecolumn',
            name='code',
            field=models.TextField(default=None),
        ),
        migrations.DeleteModel(
            name='usertable',
        ),
    ]
