# Generated by Django 3.0.5 on 2020-07-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertt', '0007_auto_20200731_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablecolumn',
            name='code',
            field=models.TextField(default=None, null=True),
        ),
    ]
