# Generated by Django 3.0.5 on 2020-07-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertt', '0008_auto_20200731_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablecolumn',
            name='code',
            field=models.TextField(default='default'),
        ),
    ]
