# Generated by Django 3.0.5 on 2020-07-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertt', '0009_auto_20200731_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetablecolumn',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='timetablecolumn',
            name='c3',
        ),
        migrations.RemoveField(
            model_name='timetablecolumn',
            name='c4',
        ),
        migrations.RemoveField(
            model_name='timetablecolumn',
            name='c5',
        ),
        migrations.RemoveField(
            model_name='timetablecolumn',
            name='c6',
        ),
        migrations.RemoveField(
            model_name='timetablecolumn',
            name='c7',
        ),
        migrations.RemoveField(
            model_name='timetablecolumn',
            name='c8',
        ),
        migrations.RemoveField(
            model_name='timetablecolumn',
            name='c9',
        ),
        migrations.RemoveField(
            model_name='timetablecolumn',
            name='code',
        ),
        migrations.RemoveField(
            model_name='timetablecolumn',
            name='row',
        ),
        migrations.AlterField(
            model_name='timetablecolumn',
            name='c1',
            field=models.CharField(default='---', max_length=2000000),
        ),
    ]
